### ISSUE TITLE
<File> tags created with wrong permissions

### ISSUE THREAD

**Issue by rkaldung** [znuny/Znuny4OTRS-Sublime#13]
When creating the SOPM file list with strg+alt+z, f the permissions do not pass the code policy. The generated permission is 644, required is 660 by the code policy.

**Comment by dennykorsukewitz** [comment]
Fixed with the great refactoring https://github.com/znuny/Znuny-Sublime/commit/dfdecd5d064f3c158fcde0eed3689bde757d0822#diff-cd58a05cfadfa3ec6efbca41643a233094ed0cb3bd4a4195dce67e01f1e002e6R40

Will be available in the next version.
Probably the 1.0.0
