### ISSUE TITLE
CustomizersLittleHelper: wrong line ending on windows

### ISSUE THREAD

**Issue by rolfschmidt** [znuny/Znuny4OTRS-Sublime#4]
Hi,
if you are using the CLH on windows it does the wrong line ending for the created files. UNIX line ending would be better.

Best regards,
Rolf

**Comment by thorsteneckel** [comment]
Should be fixed with version 0.0.21: https://github.com/znuny/Znuny4OTRS-Sublime/releases/tag/v0.0.21

Please let me know if it works for you.

**Comment by rolfschmidt** [comment]
nice fixed!
