### ISSUE TITLE
Refactor folder selection

### ISSUE THREAD

**Issue by thorsteneckel** [znuny/Znuny4OTRS-Sublime#9]
Currently the folder selection for the different shortcuts has some weak points:
- Current active folder has to get selected manually
- Currently the top folder is the start point for building folder selection which doesn't match the workflow of all devs
- Folder selection code is duplicated in multiple plugins

Therefore these changes would be desirable:
- Auto detect current folder by checking the current opened / active file
- Add a config to define the starting level of folder selection
- Create central function which handles folder detection

Additionally it would then be possible to add a shortcut to that pasts the extension name 😍

**Comment by dennykorsukewitz** [comment]
@thorsteneckel Maybe you can put that on your todo list.

**Comment by thorsteneckel** [comment]
This is labeled as "help wanted" so unless there are any volunteers I assume it's not that relevant. I'll close it for now. If someones interested in improving this let me know. I'm happy to help.
